/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dca
 */
public class Chat_serverGUI extends javax.swing.JFrame {
    private Server chatServer;
    SimpleDateFormat sdf;//Per stampare data del messaggio
    /**
     * Creates new form Chat_serverGUI
     */
    public Chat_serverGUI() {
        initComponents();
        sdf = new SimpleDateFormat("hh:mm:ss a");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_serverManager = new javax.swing.JPanel();
        jButton_start = new javax.swing.JButton();
        jTextField_portaServer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane_display = new javax.swing.JScrollPane();
        jTextArea_messaggi = new javax.swing.JTextArea();
        jLabel_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_start.setText("Avvia");
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });

        jTextField_portaServer.setText("6666");

        jLabel1.setText("Porta");

        jScrollPane_display.setAlignmentX(0.0F);
        jScrollPane_display.setAlignmentY(0.0F);

        jTextArea_messaggi.setEditable(false);
        jTextArea_messaggi.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea_messaggi.setColumns(20);
        jTextArea_messaggi.setForeground(new java.awt.Color(0, 255, 255));
        jTextArea_messaggi.setRows(5);
        jScrollPane_display.setViewportView(jTextArea_messaggi);

        javax.swing.GroupLayout jPanel_serverManagerLayout = new javax.swing.GroupLayout(jPanel_serverManager);
        jPanel_serverManager.setLayout(jPanel_serverManagerLayout);
        jPanel_serverManagerLayout.setHorizontalGroup(
            jPanel_serverManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_serverManagerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_portaServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_start)
                .addGap(31, 31, 31)
                .addComponent(jLabel_img)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_serverManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_display, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_serverManagerLayout.setVerticalGroup(
            jPanel_serverManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_serverManagerLayout.createSequentialGroup()
                .addGroup(jPanel_serverManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_start)
                    .addComponent(jTextField_portaServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_img))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_display, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_serverManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_serverManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startActionPerformed
      try{//Prendo in input la porta
        int porta = Integer.parseInt(jTextField_portaServer.getText());
        try{
          chatServer = new Server(porta,this);
          jButton_start.setEnabled(false);
          appendMessage("[SERVER]: Server connesso!");
        }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Creazione server fallita.","Attenzione", JOptionPane.ERROR_MESSAGE);    
        }  
      }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Valore inserito non valido","Attenzione", JOptionPane.ERROR_MESSAGE);    
      }
    }//GEN-LAST:event_jButton_startActionPerformed
    /*
    Aggiunge un messaggio al display (jTextArea_messaggi)
    */
    public void appendMessage(String msg){
        Date date = new Date();
        jTextArea_messaggi.append(sdf.format(date) +": "+ msg +"\n");
        jTextArea_messaggi.setCaretPosition(jTextArea_messaggi.getText().length() - 1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_serverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_start;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel_img;
    private javax.swing.JPanel jPanel_serverManager;
    private javax.swing.JScrollPane jScrollPane_display;
    private javax.swing.JTextArea jTextArea_messaggi;
    private javax.swing.JTextField jTextField_portaServer;
    // End of variables declaration//GEN-END:variables
}
